apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service
  namespace: my-ns-dev
  labels:
    app: my-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service
  namespace: my-ns-prod
  labels:
    app: my-service
