apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: my-service-db
  namespace: my-ns-dev
spec:
  vaultAuthRef: vault-auth
  mount: database
  path: creds/my-service
  rolloutRestartTargets:
    - kind: Deployment
      name: my-service
  destination:
    name: my-service-db
    create: true
    transformation:
      excludes:
        - .*
      templates:
        DB_USER:
          text: "{{ .Secrets.username }}"
        DB_PASSWORD:
          text: "{{ .Secrets.password }}"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: my-service-db
  namespace: my-ns-prod
spec:
  vaultAuthRef: vault-auth
  mount: database
  path: creds/my-service
  rolloutRestartTargets:
    - kind: Deployment
      name: my-service
  destination:
    name: my-service-db
    create: true
    transformation:
      excludes:
        - .*
      templates:
        DB_USER:
          text: "{{ .Secrets.username }}"
        DB_PASSWORD:
          text: "{{ .Secrets.password }}"
