apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: catalog-service-db
  namespace: catalog
spec:
  vaultAuthRef: vault-auth
  mount: database
  path: creds/catalog-service
  rolloutRestartTargets:
    - kind: Deployment
      name: catalog-service
  destination:
    name: catalog-service-db
    create: true
